name: Deploy to AWS S3

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to AWS s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "Install aws cli"
          pip install awscli
          echo "Deploy timestamp $(date)" > deploy-timestamp.txt
          aws s3 cp --region eu-west-1 deploy-timestamp.txt s3://a.okfn.org
          echo "Sync all files"
          aws s3 sync --cache-control max-age=7200 --region eu-west-1 a s3://a.okfn.org
